spring:
  kafka:
    producer:
      bootstrap-servers: 47.92.253.131:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: 47.92.253.131:9092