
# application.yaml里面 Kafka的配置没什么用，还需要在代码里面配置
spring:
  kafka:
    producer:
      bootstrap-servers: 47.92.253.131:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    bootstrap-servers: 47.92.253.131:9092


message:
  topic:
    name: m_topic


greeting:
  topic:
    name: g_topic


filtered:
  topic:
    name: f_topic


partitioned:
  topic:
    name: p_topic


multi:
  type:
    topic:
      name: mt_topic