spring:
  kafka:
    consumer:
      bootstrap-servers: 47.92.253.131:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-group
      enable-auto-commit: false
    bootstrap-servers: 47.92.253.131:9092
    listener:
      ack-mode: manual

server:
  port: 8081


partitioned:
  topic:
    name: p_topic